[package]
name = "adding-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name         = "addingmachine"
crate-type   = ["cdylib"]


[dependencies]
libc = "0.2"
regex = "1.5"
lazy_static = "1.4.0"

serde_json = "1.0.87"

value = { git = "https://github.com/vectordotdev/vector", default-features = false }
vrl = { git = "https://github.com/vectordotdev/vector", default-features = false  }
vrl-diagnostic = { git = "https://github.com/vectordotdev/vector", package = "vrl-diagnostic"  }

# serde stuff here
serde = { version = "1.0", features = ["derive"] }
gloo-utils = { version = "0.1", features = ["serde"] }
serde-wasm-bindgen = "0.4"


[dependencies.stdlib]
package = "vrl-stdlib"
git = "https://github.com/vectordotdev/vector"
default-features = false
features = [
    "append",
    "array",
    "assert",
    "assert_eq",
    "ceil",
    "chunks",
    "compact",
    "contains",
    "decode_base64",
    "decode_percent",
    "del",
    "downcase",
    "encode_base64",
    "encode_json",
    "encode_key_value",
    "encode_logfmt",
    "encode_percent",
    "ends_with",
    "exists",
    "filter",
    "find",
    "flatten",
    "float",
    "floor",
    "for_each",
    "format_int",
    "format_number",
    "format_timestamp",
    "get",
    "get_env_var",
    "includes",
    "ip_aton",
    "ip_cidr_contains",
    "ip_ntoa",
    "ip_ntop",
    "ip_pton",
    "ip_subnet",
    "ip_to_ipv6",
    "ipv6_to_ipv4",
    "is_array",
    "is_boolean",
    "is_empty",
    "is_float",
    "is_integer",
    "is_ipv4",
    "is_ipv6",
    "is_json",
    "is_null",
    "is_nullish",
    "is_object",
    "is_regex",
    "is_string",
    "is_timestamp",
    "join",
    "keys",
    "length",
    "map_keys",
    "map_values",
    "match",
    "match_any",
    "match_array",
    "match_datadog_query",
    "md5",
    "merge",
    "mod",
    "now",
    "object",
    "parse_apache_log",
    "parse_aws_alb_log",
    "parse_aws_cloudwatch_log_subscription_message",
    "parse_aws_vpc_flow_log",
    "parse_common_log",
    "parse_csv",
    "parse_duration",
    "parse_glog",
    "parse_int",
    "parse_json",
    "parse_key_value",
    "parse_klog",
    "parse_linux_authorization",
    "parse_logfmt",
    "parse_nginx_log",
    "parse_query_string",
    "parse_regex",
    "parse_regex_all",
    "parse_ruby_hash",
    "parse_syslog",
    "parse_timestamp",
    "parse_tokens",
    "parse_url",
    "parse_user_agent",
    "parse_xml",
    "push",
    "redact",
    "remove",
    "replace",
    "round",
    "set",
    "sha1",
    "sha2",
    "sha3",
    "slice",
    "split",
    "starts_with",
    "string",
    "strip_ansi_escape_codes",
    "strip_whitespace",
    "strlen",
    "tally",
    "tally_value",
    "tag_types_externally",
    "timestamp",
    "to_bool",
    "to_float",
    "to_int",
    "to_regex",
    "to_string",
    "to_syslog_facility",
    "to_syslog_level",
    "to_syslog_severity",
    "to_timestamp",
    "to_unix_timestamp",
    "truncate",
    "type_def",
    "unique",
    "unnest",
    "upcase",
    "values"
]